#include<stdio.h>
#include<stdlib.h>
#include<time.h>
int main(){
    int random_number1; //random number generated by computer
    srand(time(NULL));
    random_number1=rand()%100 + 1;

    
    int guess1; //user input number
    
    int i=1;
    
    printf("Welcome to the number guessing world\n");
    while(guess1!=random_number1){
    printf("\n\n");
    printf("Player 1 please enter your number between (1 to 100) : ");
    scanf("%d",&guess1);
    if(guess1<random_number1){
        printf("Guess a larger number\n");
    }
    else if(guess1>random_number1){
        printf("Guess a smaller number\n");
    }
    else{
        printf("Wohoo!! You guessed the correct number in %d turns",i);
    }
    printf("\n\n");
    i++;
}
printf("Now it's player 2's turn\nFor Player 2 to win he need to guess the number in less than %d turns",i-1);
    int guess2; //user input number
    int random_number2; //random number generated by computer
    srand(time(NULL));
    random_number2=rand()%100 + 1;

    int j=1;
    while(guess2!=random_number2){
    printf("\n\n");
    printf("Player 2 please enter your number between (1 to 100) : ");
    scanf("%d",&guess2);
    if(guess2<random_number2){
        printf("Guess a larger number\n");
    }
    else if(guess2>random_number2){
        printf("Guess a smaller number\n");
    }
    else{
        printf("Wohoo!! You guessed the correct number in %d turns",j);
    }
    printf("\n\n");
    j++;
}
    if(i-1<j-1){
        printf("Player 1 won the game");
    }
    else if(j-1>i-1){
        printf("Player 2 won the game");
    }
    else printf("The game is tied");

    printf("Thank You For Playing\n");
    printf("Bye Bye...\n");
    printf("Exiting the game....");
    
    return 0;
}